export const ROMAN_URDU_MAP: Record<string, string> = {
  // Time references
  aaj: 'today',
  kal: 'tomorrow',
  cal: 'tomorrow', // voice dictation phonetic spelling
  parso: 'in 2 days',
  abhi: 'now',
  agli: 'next',
  agla: 'next',
  pichli: 'last',
  pichla: 'last',
  is: 'this',
  // Periods
  subah: 'morning',
  subha: 'morning',
  dopeher: 'afternoon',
  dopahar: 'afternoon',
  sham: 'evening',
  shaam: 'evening',
  raat: 'night',
  // Days
  pir: 'Monday',
  peer: 'Monday',
  mangal: 'Tuesday',
  budh: 'Wednesday',
  jumeraat: 'Thursday',
  jumma: 'Friday',
  hafta: 'Saturday',
  itwaar: 'Sunday',
  // Number words
  ek: '1',
  do: '2',
  teen: '3',
  chaar: '4',
  paanch: '5',
  chhe: '6',
  saat: '7',
  aath: '8',
  nau: '9',
  das: '10',
  // Clock
  baje: "o'clock",
  minute: 'minutes',
  ghante: 'hours',
  mein: 'in',
};
